name: Test install script

on:
  push:
    branches: ["main"]
  pull_request:
    branches: []

jobs:
  run-script:
    runs-on: ${{ matrix.arch }}
    strategy:
      matrix:
        arch: ["ubuntu-latest"]
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run install script
        run: |
          ${{ github.workspace }}/install_all.sh --no-zoxide
          echo "${HOME}/.local/bin:${PATH}" >> "${GITHUB_PATH}"
          echo "${HOME}/.fzf/bin:${PATH}" >> "${GITHUB_PATH}"

      - name: Ensure fzf installed
        run: |
          source ~/.bashrc
          cat ~/.bashrc
          echo $PATH
          which fzf

      - name: Ensure helix installed
        run: which hx

