name: Test install script

on:
  push:
    branches: ["main"]
  pull_request:
    branches: []

jobs:
  run-script:
    runs-on: ${{ matrix.arch }}
    strategy:
      matrix:
        arch: ["ubuntu-latest"]
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run install script
        run: |
          ${{ github.workspace }}/install_all.sh
          echo "${HOME}/.local/bin:${PATH}" >> "${GITHUB_PATH}"

      - name: check bruh
        run: cat ~/.bashrc

      - name: check bruh2
        run: echo $PATH

      - name: Ensure fzf installed
        run: |
          source ~/.bashrc
          which fzf

      - name: Ensure helix installed
        run: which hx

