name: Test install script

on:
  push:
    branches: ["main"]
  pull_request:
    branches: []

jobs:
  run-script:
    runs-on: ${{ matrix.arch }}
    strategy:
      matrix:
        arch: ["ubuntu-latest"]
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run install script
        run: ./setup/install_all.sh
      

